[book]
authors = ["Erik Johnston"]
language = "en"
multilingual = false
src = "src"
title = "Matrix HomeServer Implementation Guide"

[output.html]
theme = "../theme"
git-repository-url = "https://github.com/matrix-org/matrix.org/tree/erikj/imple_guide/implementation-guides/server"

[preprocessor.links]

[preprocessor.index]
