# GHA workflow which publishes previews of the matrix.org website PRs to netlify.
#
# We keep this in a separate workflow to the main website build, because it
# requires access to the Netlify secret. By having it run on `workflow_run`, we
# will only use the workflow definition file on the default branch, so we can
# ensure that the secret can't be exfiltrated.
#

name: Upload Preview Build to Netlify
on:
  workflow_run:
    workflows: ["🌐 Build the matrix.org website"]
    types: [completed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'pull_request'
    steps:
      - name: '📥 Download artifact'
        uses: dawidd6/action-download-artifact@af92a8455a59214b7b932932f2662fdefbd78126 # v2.15.0
        with:
          workflow: main.yaml
          run_id: ${{ github.event.workflow_run.id }}
          name: merged-content-artifact

      - name: "📦 Extract Artifacts"
        run: tar -xzvf content.tar.gz && rm content.tar.gz

      - name: "📤 Deploy to Netlify"
        id: netlify
        # v1.2.2
        uses: nwtgck/actions-netlify@f517512ae75beec8896aa7b027c1c72f01816200
        with:
          publish-dir: content
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: false
          alias: pr${{ steps.readctx.outputs.prnumber }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 15

      - name: "📤 Deploy to Netlify"
        uses: matrix-org/netlify-pr-preview@v1
        with:
          path: content
          owner: ${{ github.event.workflow_run.head_repository.owner.login }}
          branch: ${{ github.event.workflow_run.head_branch }}
          revision: ${{ github.event.workflow_run.head_sha }}
          token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          site_id: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 15


